# Generated by Django 2.1.1 on 2019-06-23 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0002_adventurerecords_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventurerecords',
            name='blacktower',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adventurerecords',
            name='bossroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adventurerecords',
            name='capitalroad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adventurerecords',
            name='cave',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adventurerecords',
            name='desert',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adventurerecords',
            name='devilzone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adventurerecords',
            name='holder',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adventurerecords',
            name='mazetower',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adventurerecords',
            name='palace',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adventurerecords',
            name='storybook',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adventurerecords',
            name='village',
            field=models.IntegerField(default=0),
        ),
    ]
