# Generated by Django 2.1.1 on 2019-06-23 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0003_auto_20190623_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventurerecords',
            name='holder',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
